
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports: ["5432:5432"]

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]

  app:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    env_file: .env
    depends_on: [db, redis]
    ports: ["8000:8000"]

  worker:
    build: .
    command: python matcher/service.py
    volumes:
      - .:/code
    env_file: .env
    depends_on: [db, redis]

volumes:
  pgdata:
